### ISSUE TITLE
Gathering information

### ISSUE THREAD

**Issue by Platon377** [Platon377/Basics-of-SE#1]
The following subtasks are included:
- [x] 1) [analyse the domain area](https://github.com/Platon377/Basics-of-SE/issues/2#issue-2629225792)
- [ ] 2) [write software requirements specificatiin](https://github.com/Platon377/Basics-of-SE/issues/3#issue-2629239119)
- [x] 3) [draw a Use Case diagram to show the functionality of the system](https://github.com/Platon377/Basics-of-SE/issues/4#issue-2629242852)
